// Generated by CoffeeScript 1.9.3

/**
 * 首页的控制器
 * @author pangjg
 * @date 2015-08-20 21:03:31
 */
module.exports = {

  /* 首页 */
  get_index: function(req, res) {
    return res.send("Index page!");
  }
};
